name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get specific version CMake, v3.21.2
      uses: lukka/get-cmake@v3.21.2
    
    - name: Get boost
      run: sudo apt-get install libboost-all-dev

    - name: Get curl etc
      run: sudo apt-get install libssl-dev libcurl4-openssl-dev

    - name: run build
      run: mkdir build && cd build && cmake ../ && cmake --build .
