name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get specific version CMake, v3.21.2
      uses: lukka/get-cmake@v3.21.2
    
    - name: update pkg manager
      run: sudo apt-get update

    - name: Get boost
      run: sudo apt-get install libboost-all-dev

    # curl is built from source now. No need to have these libs
    # - name: Get curl etc
    #   run: sudo apt-get install libssl-dev libcurl4-openssl-dev
    
    - name: run cmake
      run: mkdir build && cd build && cmake ../

    - name: run build
      run: cd build && cmake --build .
    
    - name: run test
      run: cd build && ctest

    - name: get valgrind
      run: sudo apt-get install valgrind

    - name: check test memory corruption
      run: cd build && valgrind ./json/test/json_test

    - name: Save main exe
      uses: actions/upload-artifact@v2
      with:
        name: main-exe
        path: build/examples/cpp-openapi/main
        retention-days: 1
      

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      #- uses: actions/checkout@v2

      - name: download main executable
        uses: actions/download-artifact@master
        with:
          name: main-exe
          path: build/examples/cpp-openapi
      
      - name: make artifact executable
        run: sudo chmod +x ./build/examples/cpp-openapi/main

      # run go-swagger example server
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Get go-swagger repo
        run: git clone --depth 1 https://github.com/go-swagger/go-swagger.git
    
      - name: build server
        run: cd go-swagger && go build -o ../server examples/auto-configure/cmd/a-to-do-list-application-server/main.go
      
      - name: run server
        run: ./server --port=12345 &

      - name: run main exe
        run: ./build/examples/cpp-openapi/main
      